---
# file: roles/hardening/tasks/hardening_debian.yml

- name: Install recommended security packages
  action: apt pkg={{ item }} state=latest
  with_items:
    - fail2ban
    - logwatch
    - unattended-upgrades
    - lynis

- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart ssh

- name: Make logwatch mail weekly
  action: lineinfile dest=/etc/cron.weekly/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{ hardening.admin_email }} --detail high" state=present create=yes

- name: Enable automatic security updates
  apt: pkg=unattended-upgrades
       state=latest
       update_cache=yes

- name: Configure automatic security update
  template: dest=/etc/apt/apt.conf.d/50unattended-upgrades
       src=unattended-upgrades.j2
       backup=yes

- name: Configure automatic updates settings
  template: dest=/etc/apt/apt.conf.d/02periodic
       src=apt-periodic.j2
       backup=yes

