---
# file: roles/php-ci/tasks/jenkins.yml

# Provides add-apt-repository
- name: Install python-software-properties
  sudo: yes
  apt: pkg=python-software-properties state=installed
  tags: php-ci

# Add Jenkins repository key
- name: Add Jenkins apt-key
  sudo: yes
  action: apt_key url={{ jenkins.deb.key }} state=present
  tags: php-ci

# Add Jenkins repository
- name: Add Jenkins repository
  sudo: yes
  apt_repository: repo='{{ jenkins.deb.repo }}' state=present
  tags: php-ci

- name: Install Jenkins
  apt: pkg=jenkins state=installed
  tags: php-ci

- name: Install required tools 
  action: apt pkg={{ item }} state=latest
  with_items:
      - openjdk-6-jdk
      - php5
      - php-pear
      - php5-xsl
      - php5-dev
      - ant
      - curl
      - php5-xdebug
  tags: php-ci
  
- command: pear config-set auto_discover 1
  ignore_errors: yes
  tags: php-cli 
- command: pear channel-discover pear.phpunit.de
  ignore_errors: yes
  tags: php-ci
- command: pear channel-discover pear.symfony-project.com
  ignore_errors: yes
  tags: php-ci
- command: pear channel-discover pear.pdepend.org
  ignore_errors: yes
  tags: php-ci
- command: pear channel-discover pear.phpmd.org
  ignore_errors: yes
  tags: php-ci
- command: pear channel-discover components.ez.no
  ignore_errors: yes
  tags: php-ci
- command: pear channel-discover pear.symfony.com
  ignore_errors: yes
  tags: php-ci
- command: pear update-channels
  tags: php-ci
- command: pear upgrade-all
  tags: php-ci
- command: pear install -f pear.netpirates.net/phpDox
  ignore_errors: yes
  tags: php-ci
- command: pear install pear.symfony.com/Yaml
  ignore_errors: yes
  tags: php-ci
- command: pear install phpmd/PHP_PMD
  ignore_errors: yes
  tags: php-ci
- command: pear install --alldeps pear.phpunit.de/PHPUnit
  ignore_errors: yes
  tags: php-ci
- command: pear install --alldeps pear.phpunit.de/PHPUnit_Selenium
  ignore_errors: yes
  tags: php-ci
- command: pear install --alldeps pear.phpunit.de/phploc
  ignore_errors: yes
  tags: php-ci
- command: pear install --alldeps pear.phpunit.de/ppw
  ignore_errors: yes
  tags: php-ci  
- command: pear install --alldeps pear.phpunit.de/phpcpd
  ignore_errors: yes
  tags: php-ci
- command: pear install --force --alldeps pear.phpunit.de/DbUnit
  ignore_errors: yes
  tags: php-ci
- command: pear install --force --alldeps pear.phpunit.de/PHPUnit_MockObject
  ignore_errors: yes
  tags: php-ci
- command: pear install --force --alldeps pear.phpunit.de/PHPUnit_Story
  ignore_errors: yes
  tags: php-ci
- command: pear install PHP_CodeSniffer
  ignore_errors: yes
  tags: php-ci

- file: path=/var/lib/jenkins/updates state=directory owner=jenkins
  ignore_errors: yes
  tags: php-ci

- name: Workaround for updates issues with CLI
  action: command wget -O /var/lib/jenkins/updates/default.json http://updates.jenkins-ci.org/update-center.json
  tags: php-ci

- name: Clean default.json file
  lineinfile: dest=/var/lib/jenkins/updates/default.json regexp='updateCenter.*\(' state=absent
  tags: php-ci

- name: Clean default.json file again
  lineinfile: dest=/var/lib/jenkins/updates/default.json regexp='\);' state=absent
  tags: php-ci

- name: Workaround for updates issues with CLI
  action: command chown -R jenkins:nogroup /var/lib/jenkins/updates
  notify: restart jenkins
  tags: php-ci

- wait_for: port=8080 delay=20
  tags: php-ci
  
- name: Get Jenkins cli
  action: command wget http://localhost:8080/jnlpJars/jenkins-cli.jar
  tags: php-ci

- name: Get Jenkins plugins
  action: command java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin git checkstyle cloverphp dry htmlpublisher jdepend plot pmd violations xunit
  ignore_errors: yes
  tags: php-ci

- file: path=/var/lib/jenkins/jobs/php-template state=directory owner=jenkins
  tags: php-ci
- copy: src=config.xml dest=/var/lib/jenkins/jobs/php-template/config.xml owner=jenkins
  tags: php-ci
- action: command java -jar jenkins-cli.jar -s http://localhost:8080 reload-configuration
  tags: php-ci

- wait_for: port=8080 delay=20
  tags: php-ci
  
- name: Start the demo build
  action: command java -jar jenkins-cli.jar -s http://localhost:8080 build "php-template"
  ignore_errors: yes
  tags: php-ci